'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Backpack, Ban, Check, CircleDollarSign, Clock3, Coins, Crosshair, History, LayoutDashboard, LoaderCircle, MapPinned, MessageSquareOff, Monitor, PackageOpen, Radio, RefreshCw, ShieldAlert, ShieldCheck, UserRound, WifiOff, X, type LucideIcon } from 'lucide-react';
import { PanelExtendedNav } from './PanelExtendedNav';

type Row = Record<string, string|number|boolean|null|undefined>;
type Payload = { player:Row; inventory:Row[]; locations:Row[]; stationary:Row|null; trades:Row[]; tradeItems:Row[]; sanctions:Row[] };

const sanctionOptions = [
  ['account','Hesabı Banla','Hesaptaki tüm karakterlerin girişini engeller.'],
  ['character','Karakteri Banla','Yalnızca seçili karakterin girişini engeller.'],
  ['hwid','HWID Ban','Aynı donanım kimliğiyle giriş yapılmasını engeller.'],
  ['pc','PC Ban','Oyun istemcisinin PC kimliğini engeller.'],
  ['ip','İnternet / IP Ban','Son görülen internet adresinden girişi engeller.'],
  ['mute','Sadece Sessize Al','Oyuncu oyunda kalır fakat sohbet mesajı gönderemez.'],
] as const;
const durationOptions = [['60','1 saat'],['1440','1 gün'],['4320','3 gün'],['10080','7 gün'],['43200','30 gün'],['permanent','Süresiz']] as const;

function dateText(value:unknown){if(!value)return '—';const date=new Date(String(value));return Number.isNaN(date.getTime())?'—':date.toLocaleString('tr-TR')}
function numberText(value:unknown){return Number(value??0).toLocaleString('tr-TR')}
function durationText(seconds:unknown){const total=Math.max(0,Number(seconds??0));const days=Math.floor(total/86400);const hours=Math.floor(total%86400/3600);const minutes=Math.floor(total%3600/60);return [days&&`${days}g`,hours&&`${hours}s`,minutes&&`${minutes}dk`].filter(Boolean).join(' ')||'< 1 dk'}

export function PlayerDetailPage({playerId,user}:{playerId:number;user:{name:string;email:string}}){
  const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [toast,setToast]=useState('');
  const [type,setType]=useState('account');const [duration,setDuration]=useState('10080');const [reason,setReason]=useState('');
  const initials=user.name.split(/\s+/).map((part)=>part[0]).join('').slice(0,2).toUpperCase();
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/players/${playerId}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error??'Oyuncu alınamadı.');setData(result)}catch(reason){setError(reason instanceof Error?reason.message:'Bağlantı hatası.')}finally{setLoading(false)}},[playerId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer)},[toast]);
  const activeSanctions=useMemo(()=>data?.sanctions.filter((row)=>row.active===1&&(!row.expires_at||new Date(row.expires_at)>new Date()))??[],[data]);
  async function sanction(){setSaving(true);try{const response=await fetch(`/api/players/${playerId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'sanction',sanctionType:type,durationMinutes:duration==='permanent'?null:Number(duration),reason})});const result=await response.json();if(!response.ok)throw new Error(result.error);setToast(type==='mute'?'Oyuncu sessize alındı; sohbet gönderimi kapatıldı.':'Yaptırım kaydedildi ve oyun eşitlemesine alındı.');setReason('');await load()}catch(reason){setToast(reason instanceof Error?reason.message:'Yaptırım uygulanamadı.')}finally{setSaving(false)}}
  async function revoke(id:number){setSaving(true);try{const response=await fetch(`/api/players/${playerId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'revoke',sanctionId:id})});const result=await response.json();if(!response.ok)throw new Error(result.error);setToast('Yaptırım kaldırıldı.');await load()}catch(reason){setToast(reason instanceof Error?reason.message:'Yaptırım kaldırılamadı.')}finally{setSaving(false)}}
  const player=data?.player;
  return <div className="app-shell player-detail-shell"><aside className="sidebar"><div className="brand"><img src="/metin3-logo.png" alt="Metin 3"/><span>YÖNETİM PANELİ</span></div><nav className="nav-list"><p className="nav-section">OYUNCU DENETİMİ</p><Link className="nav-item" href="/panel"><LayoutDashboard/><span>Kontrol Merkezi</span></Link><Link className="nav-item active" href="/panel?view=players"><UserRound/><span>Oyuncular</span></Link><Link className="nav-item" href="/panel/system/trades"><CircleDollarSign/><span>Ticaret Kayıtları</span></Link><PanelExtendedNav/></nav><div className="server-card"><div className="server-title"><ShieldCheck/> Canlı Oyuncu Verisi</div><div className="server-row"><span><i/> Envanter eşitlemesi</span><strong>Hazır</strong></div><div className="server-row"><span><i/> Konum geçmişi</span><strong>Etkin</strong></div><small>Boş alanlar tahmin edilmez; oyun istemcisinden veri geldikçe doldurulur.</small></div><div className="admin-card"><div className="avatar">{initials}</div><div><strong>{user.name}</strong><span>{user.email}</span></div></div></aside><main className="main"><header className="topbar detail-topbar"><Link className="detail-back" href="/panel?view=players"><ArrowLeft/> Oyuncular</Link><div className="top-actions"><button className="icon-button" onClick={()=>void load()}><RefreshCw className={loading?'spin':''}/></button><div className="avatar small">{initials}</div></div></header><div className="content player-detail-content">{loading?<div className="loading"><LoaderCircle className="spin"/><strong>Oyuncu kartı hazırlanıyor</strong></div>:error?<section className="detail-error"><X/><h1>Oyuncu açılamadı</h1><p>{error}</p></section>:player&&data&&<>
    <section className="player-hero"><div className="player-avatar"><UserRound/></div><div className="player-heading"><div className="detail-badges"><span>#{player.id}</span><span>{player.empire}</span><span>{player.character_class}</span><span className={player.online?'enabled':'disabled'}>{player.online?'Çevrimiçi':'Çevrimdışı'}</span>{activeSanctions.length>0&&<span className="danger">{activeSanctions.length} aktif yaptırım</span>}</div><h1>{player.character_name}</h1><p>@{player.account} · Seviye {numberText(player.level)} · Son görülme {dateText(player.last_seen)}</p></div><div className="player-live-location"><MapPinned/><span>Son Konum</span><strong>{player.last_map_code||'Henüz gönderilmedi'}</strong><small>{player.last_map_code?`X ${numberText(player.last_x)} · Y ${numberText(player.last_y)}`:'Oyun eşitlemesi bekleniyor'}</small></div></section>
    <section className="player-stat-grid"><article><Coins/><span>Yang</span><strong>{numberText(player.yang)}</strong></article><article><CircleDollarSign/><span>Won</span><strong>{numberText(player.won)}</strong></article><article><Backpack/><span>Envanter</span><strong>{data.inventory.length} kayıt</strong></article><article><History/><span>Son Ticaret</span><strong>{dateText(data.trades[0]?.created_at)}</strong></article><article><Crosshair/><span>En Uzun Sabit Kalma</span><strong>{durationText(data.stationary?.stationary_seconds)}</strong></article></section>
    <section className="player-detail-grid"><article className="panel player-section inventory-section"><SectionTitle icon={Backpack} kicker="CANLI ENVANTER" title="Eşyalar ve Ekipman"/><div className="inventory-grid">{data.inventory.map((item)=><div className={`inventory-card ${item.equipped?'equipped':''}`} key={item.id}><div className="inventory-slot">{item.equipped?'E':'#'+item.slot}</div><PackageOpen/><div><strong>{item.item_name}</strong><span>VNUM {item.item_vnum} · {numberText(item.count)} adet</span></div></div>)}{!data.inventory.length&&<Empty text="Oyun henüz bu karakterin envanterini göndermedi."/>}</div></article>
    <article className="panel player-section"><SectionTitle icon={MapPinned} kicker="HAREKET ANALİZİ" title="Son Bulunduğu Haritalar"/><div className="timeline-list">{data.locations.map((row)=><div key={row.id}><i/><span><strong>{row.map_code}</strong><small>X {numberText(row.x)} · Y {numberText(row.y)}</small></span><span><b>{durationText(row.duration_seconds)}</b><small>{dateText(row.entered_at)}</small></span></div>)}{!data.locations.length&&<Empty text="Konum geçmişi henüz oluşmadı."/>}</div>{data.stationary&&<div className="stationary-card"><Clock3/><div><span>En uzun süre sabit kaldığı nokta</span><strong>{data.stationary.map_code} · X {numberText(data.stationary.x)} / Y {numberText(data.stationary.y)}</strong></div><b>{durationText(data.stationary.stationary_seconds)}</b></div>}</article>
    <article className="panel player-section"><SectionTitle icon={CircleDollarSign} kicker="EKONOMİ DENETİMİ" title="Son Ticaret Kayıtları"/><div className="trade-list">{data.trades.map((trade)=><div key={trade.id}><div><strong>{trade.giver} → {trade.receiver}</strong><span>{dateText(trade.created_at)} · IP {trade.ip_address||'yok'}</span></div><div><b>{numberText(trade.yang)} Yang</b><span>{data.tradeItems.filter((item)=>item.trade_id===trade.id).map((item)=>`${item.item_name||'#'+item.item_vnum} ×${item.count}`).join(', ')||'İtem yok'}</span></div></div>)}{!data.trades.length&&<Empty text="Bu karakter için ticaret kaydı bulunmuyor."/>}</div></article>
    <article className="panel player-section security-section"><SectionTitle icon={ShieldAlert} kicker="GÜVENLİK" title="Yaptırım Merkezi"/><div className="security-identifiers"><span><Monitor/>PC <b>{player.pc_id||'Veri yok'}</b></span><span><Radio/>HWID <b>{player.hwid||'Veri yok'}</b></span><span><WifiOff/>IP <b>{player.last_ip||'Veri yok'}</b></span></div><div className="sanction-builder"><label><span>Yaptırım türü</span><select value={type} onChange={(event)=>setType(event.target.value)}>{sanctionOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small>{sanctionOptions.find(([value])=>value===type)?.[2]}</small></label><label><span>Süre</span><select value={duration} onChange={(event)=>setDuration(event.target.value)}>{durationOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="reason"><span>Sebep</span><input value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Yönetici notu ve oyuncuya gösterilecek sebep"/></label><button className={type==='mute'?'primary mute-action':'primary danger-action'} disabled={saving} onClick={()=>void sanction()}>{saving?<LoaderCircle className="spin"/>:type==='mute'?<MessageSquareOff/>:<Ban/>}{type==='mute'?'Sessize Al':'Yaptırımı Uygula'}</button></div><div className="sanction-list">{data.sanctions.map((row)=><div key={row.id} className={row.active?'active':''}><span className="sanction-type">{row.sanction_type}</span><div><strong>{row.reason}</strong><small>{row.target_value} · {dateText(row.created_at)} · {row.expires_at?`Bitiş ${dateText(row.expires_at)}`:'Süresiz'}</small></div>{row.active?<button onClick={()=>void revoke(row.id)}><ShieldCheck/>Kaldır</button>:<span className="revoked">Kaldırıldı</span>}</div>)}{!data.sanctions.length&&<Empty text="Oyuncunun yaptırım geçmişi yok."/>}</div></article>
  </section></>}</div></main>{toast&&<div className="toast"><Check/>{toast}</div>}</div>
}

function SectionTitle({icon:Icon,kicker,title}:{icon:LucideIcon;kicker:string;title:string}){return <header><div className="section-icon red"><Icon/></div><div><span>{kicker}</span><h2>{title}</h2></div></header>}
function Empty({text}:{text:string}){return <div className="player-empty"><PackageOpen/><span>{text}</span></div>}
